export const CITY_COORDINATES: Record<string, { lat: number; lng: number; radius: number; isSmall?: boolean }> = {

  // ── ORAȘE MARI ────────────────────────────────────────────────────────────
  'Cluj-Napoca':     { lat: 46.7712, lng: 23.6236, radius: 15000 },
  'București':       { lat: 44.4268, lng: 26.1025, radius: 25000 },
  'Timișoara':       { lat: 45.7489, lng: 21.2087, radius: 18000 },
  'Iași':            { lat: 47.1585, lng: 27.6014, radius: 15000 },
  'Brașov':          { lat: 45.6427, lng: 25.5887, radius: 15000 },
  'Constanța':       { lat: 44.1765, lng: 28.6480, radius: 15000 },
  'Craiova':         { lat: 44.3302, lng: 23.7949, radius: 12000 },
  'Galați':          { lat: 45.4353, lng: 28.0080, radius: 12000 },
  'Oradea':          { lat: 47.0458, lng: 21.9189, radius: 15000 },
  'Ploiești':        { lat: 44.9365, lng: 26.0226, radius: 12000 },
  'Brăila':          { lat: 45.2692, lng: 27.9574, radius: 10000 },
  'Arad':            { lat: 46.1700, lng: 21.3150, radius: 12000 },
  'Sibiu':           { lat: 45.7983, lng: 24.1256, radius: 12000 },
  'Bacău':           { lat: 46.5670, lng: 26.9146, radius: 12000 },
  'Târgu Mureș':     { lat: 46.5386, lng: 24.5575, radius: 12000 },
  'Baia Mare':       { lat: 47.6567, lng: 23.5681, radius: 10000 },
  'Buzău':           { lat: 45.1500, lng: 26.8167, radius: 8000  },
  'Satu Mare':       { lat: 47.7914, lng: 22.8844, radius: 10000 },
  'Râmnicu Vâlcea':  { lat: 45.0996, lng: 24.3690, radius: 8000  },
  'Pitești':         { lat: 44.8565, lng: 24.8692, radius: 10000 },
  'Drobeta-Turnu Severin': { lat: 44.6333, lng: 22.6567, radius: 8000 },
  'Suceava':         { lat: 47.6520, lng: 26.2547, radius: 10000 },
  'Piatra Neamț':    { lat: 46.9258, lng: 26.3717, radius: 8000  },
  'Târgu Jiu':       { lat: 45.0333, lng: 23.2833, radius: 8000  },
  'Alba Iulia':      { lat: 46.0669, lng: 23.5799, radius: 10000 },
  'Deva':            { lat: 45.8833, lng: 22.9000, radius: 8000  },
  'Bistrița':        { lat: 47.1333, lng: 24.5000, radius: 10000 },
  'Focșani':         { lat: 45.6969, lng: 27.1876, radius: 8000  },
  'Tulcea':          { lat: 45.1787, lng: 28.8042, radius: 8000  },
  'Sighișoara':      { lat: 46.2197, lng: 24.7937, radius: 6000  },
  'Sfântu Gheorghe': { lat: 45.8670, lng: 25.7870, radius: 8000  },
  'Miercurea Ciuc':  { lat: 46.3578, lng: 25.8024, radius: 8000  },
  'Zalău':           { lat: 47.1897, lng: 23.0569, radius: 8000  },
  'Turda':           { lat: 46.5667, lng: 23.7833, radius: 6000  },
  'Dej':             { lat: 47.1508, lng: 23.8697, radius: 6000  },
  'Slobozia':        { lat: 44.5642, lng: 27.3631, radius: 7000  },
  'Alexandria':      { lat: 43.9767, lng: 25.3342, radius: 7000  },
  'Vaslui':          { lat: 46.6411, lng: 27.7297, radius: 7000  },
  'Reșița':          { lat: 45.2961, lng: 21.8894, radius: 8000  },
  'Târgoviște':      { lat: 44.9272, lng: 25.4572, radius: 8000  },
  'Giurgiu':         { lat: 43.9000, lng: 25.9667, radius: 7000  },
  'Călărași':        { lat: 44.2072, lng: 27.3317, radius: 7000  },
  'Drobeta-T.S.':    { lat: 44.6333, lng: 22.6567, radius: 8000  },
  'Roman':           { lat: 46.9186, lng: 26.9258, radius: 7000  },
  'Fălticeni':       { lat: 47.4583, lng: 26.3000, radius: 5000  },

  // ── ORAȘE MEDII ───────────────────────────────────────────────────────────
  'Petroșani':       { lat: 45.4178, lng: 23.3644, radius: 6000  },
  'Lugoj':           { lat: 45.6881, lng: 21.9036, radius: 6000  },
  'Mediaș':          { lat: 46.1622, lng: 24.3519, radius: 6000  },
  'Câmpina':         { lat: 45.1167, lng: 25.7333, radius: 5000  },
  'Orăștie':         { lat: 45.8333, lng: 23.2000, radius: 4000  },
  'Câmpulung':       { lat: 45.2653, lng: 25.0486, radius: 5000  },
  'Drăgășani':       { lat: 44.6622, lng: 24.2664, radius: 4000  },
  'Curtea de Argeș': { lat: 45.1381, lng: 24.6758, radius: 4000  },
  'Moreni':          { lat: 44.9833, lng: 25.6500, radius: 4000  },
  'Fetești':         { lat: 44.3739, lng: 27.8397, radius: 5000  },
  'Caracal':         { lat: 44.1167, lng: 24.3500, radius: 5000  },

  // ── ORAȘE MICI — concurență ZERO ─────────────────────────────────────────
  // Cluj
  'Câmpia Turzii':   { lat: 46.5573, lng: 23.8831, radius: 5000, isSmall: true },
  'Gherla':          { lat: 47.0333, lng: 23.9000, radius: 5000, isSmall: true },
  'Huedin':          { lat: 46.8833, lng: 22.9000, radius: 4000, isSmall: true },
  'Florești CJ':     { lat: 46.7430, lng: 23.5116, radius: 4000, isSmall: true },
  // Brașov
  'Săcele':          { lat: 45.6167, lng: 25.7000, radius: 5000, isSmall: true },
  'Codlea':          { lat: 45.7000, lng: 25.4500, radius: 4000, isSmall: true },
  'Zărnești':        { lat: 45.5500, lng: 25.3333, radius: 4000, isSmall: true },
  'Râșnov':          { lat: 45.5858, lng: 25.4558, radius: 4000, isSmall: true },
  'Predeal':         { lat: 45.5058, lng: 25.5783, radius: 3000, isSmall: true },
  // Sibiu
  'Cisnădie':        { lat: 45.7083, lng: 24.1550, radius: 4000, isSmall: true },
  'Avrig':           { lat: 45.7083, lng: 24.3667, radius: 3000, isSmall: true },
  'Tălmaciu':        { lat: 45.6333, lng: 24.2833, radius: 3000, isSmall: true },
  'Ocna Sibiului':   { lat: 45.8500, lng: 24.0333, radius: 3000, isSmall: true },
  // Mureș
  'Reghin':          { lat: 46.7756, lng: 24.7025, radius: 5000, isSmall: true },
  'Luduș':           { lat: 46.4769, lng: 24.1092, radius: 4000, isSmall: true },
  'Iernut':          { lat: 46.4500, lng: 24.2333, radius: 3000, isSmall: true },
  'Sovata':          { lat: 46.5972, lng: 25.0833, radius: 3000, isSmall: true },
  // Alba
  'Sebeș':           { lat: 45.9567, lng: 23.5675, radius: 5000, isSmall: true },
  'Blaj':            { lat: 46.1750, lng: 23.9167, radius: 4000, isSmall: true },
  'Cugir':           { lat: 45.8333, lng: 23.3667, radius: 4000, isSmall: true },
  'Zlatna':          { lat: 46.1167, lng: 23.2167, radius: 3000, isSmall: true },
  'Abrud':           { lat: 46.2667, lng: 23.0500, radius: 3000, isSmall: true },
  // Bihor
  'Beiuș':           { lat: 46.6706, lng: 22.3525, radius: 4000, isSmall: true },
  'Salonta':         { lat: 46.7992, lng: 21.6503, radius: 4000, isSmall: true },
  'Marghita':        { lat: 47.3503, lng: 22.3228, radius: 4000, isSmall: true },
  'Aleșd':           { lat: 47.0500, lng: 22.4000, radius: 3000, isSmall: true },
  'Valea lui Mihai': { lat: 47.5167, lng: 22.1333, radius: 3000, isSmall: true },
  // Satu Mare
  'Carei':           { lat: 47.6833, lng: 22.4667, radius: 5000, isSmall: true },
  'Negrești-Oaș':    { lat: 47.8711, lng: 23.4319, radius: 4000, isSmall: true },
  'Tășnad':          { lat: 47.4583, lng: 22.5833, radius: 4000, isSmall: true },
  'Ardud':           { lat: 47.6333, lng: 22.8833, radius: 3000, isSmall: true },
  // Maramureș
  'Sighetul Marmației': { lat: 47.9289, lng: 23.8889, radius: 6000, isSmall: true },
  'Vișeu de Sus':    { lat: 47.7167, lng: 24.4167, radius: 4000, isSmall: true },
  'Borșa':           { lat: 47.6569, lng: 24.6614, radius: 4000, isSmall: true },
  'Câmpulung la Tisa': { lat: 47.9333, lng: 23.6833, radius: 3000, isSmall: true },
  'Seini':           { lat: 47.7500, lng: 23.2833, radius: 3000, isSmall: true },
  // Timiș
  'Deta':            { lat: 45.3972, lng: 21.2250, radius: 3000, isSmall: true },
  'Jimbolia':        { lat: 45.7833, lng: 20.7167, radius: 3000, isSmall: true },
  'Sânnicolau Mare': { lat: 46.0742, lng: 20.6278, radius: 4000, isSmall: true },
  'Buziaș':          { lat: 45.6500, lng: 21.6000, radius: 3000, isSmall: true },
  'Recaș':           { lat: 45.7667, lng: 21.5167, radius: 3000, isSmall: true },
  // Arad
  'Ineu':            { lat: 46.4333, lng: 21.8500, radius: 3000, isSmall: true },
  'Lipova':          { lat: 46.0833, lng: 21.6833, radius: 3000, isSmall: true },
  'Nădlac':          { lat: 46.1667, lng: 20.7500, radius: 3000, isSmall: true },
  'Chișineu-Criș':   { lat: 46.5167, lng: 21.5167, radius: 3000, isSmall: true },
  'Curtici':         { lat: 46.3500, lng: 21.2833, radius: 3000, isSmall: true },
  // Hunedoara
  'Brad':            { lat: 46.1267, lng: 22.7817, radius: 3000, isSmall: true },
  'Simeria':         { lat: 45.8500, lng: 23.0167, radius: 3000, isSmall: true },
  'Vulcan':          { lat: 45.3833, lng: 23.2833, radius: 4000, isSmall: true },
  'Lupeni':          { lat: 45.3500, lng: 23.2333, radius: 4000, isSmall: true },
  'Uricani':         { lat: 45.3333, lng: 23.2000, radius: 3000, isSmall: true },
  // Prahova
  'Sinaia':          { lat: 45.3500, lng: 25.5500, radius: 4000, isSmall: true },
  'Bușteni':         { lat: 45.4000, lng: 25.5333, radius: 3000, isSmall: true },
  'Azuga':           { lat: 45.4500, lng: 25.5500, radius: 2500, isSmall: true },
  'Vălenii de Munte':{ lat: 45.1833, lng: 26.0333, radius: 4000, isSmall: true },
  'Băicoi':          { lat: 44.9833, lng: 25.8667, radius: 4000, isSmall: true },
  // Constanța
  'Mangalia':        { lat: 43.8122, lng: 28.5847, radius: 5000, isSmall: true },
  'Eforie Nord':     { lat: 44.0608, lng: 28.6308, radius: 3000, isSmall: true },
  'Năvodari':        { lat: 44.3228, lng: 28.6164, radius: 5000, isSmall: true },
  'Techirghiol':     { lat: 44.0333, lng: 28.5833, radius: 3000, isSmall: true },
  'Cernavodă':       { lat: 44.3333, lng: 28.0333, radius: 4000, isSmall: true },
  'Ovidiu':          { lat: 44.2833, lng: 28.5667, radius: 4000, isSmall: true },
  'Murfatlar':       { lat: 44.1667, lng: 28.4000, radius: 3000, isSmall: true },
  // Suceava
  'Câmpulung Moldovenesc': { lat: 47.5272, lng: 25.5592, radius: 4000, isSmall: true },
  'Rădăuți':         { lat: 47.8453, lng: 25.9197, radius: 5000, isSmall: true },
  'Vatra Dornei':    { lat: 47.3556, lng: 25.3600, radius: 4000, isSmall: true },
  'Gura Humorului':  { lat: 47.5500, lng: 25.8833, radius: 4000, isSmall: true },
  'Siret':           { lat: 47.9500, lng: 26.0667, radius: 3000, isSmall: true },
  'Solca':           { lat: 47.6833, lng: 25.8500, radius: 2500, isSmall: true },
  // Neamț
  'Târgu Neamț':     { lat: 47.2000, lng: 26.3667, radius: 4000, isSmall: true },
  'Bicaz':           { lat: 46.8667, lng: 26.0833, radius: 3000, isSmall: true },
  'Roznov':          { lat: 46.8500, lng: 26.5000, radius: 3000, isSmall: true },
  // Bacău
  'Onești':          { lat: 46.2500, lng: 26.7833, radius: 6000, isSmall: true },
  'Moinești':        { lat: 46.4667, lng: 26.4833, radius: 5000, isSmall: true },
  'Comănești':       { lat: 46.4167, lng: 26.4333, radius: 4000, isSmall: true },
  'Slănic Moldova':  { lat: 46.2167, lng: 26.4333, radius: 3000, isSmall: true },
  // Iași
  'Pașcani':         { lat: 47.2500, lng: 26.7167, radius: 5000, isSmall: true },
  'Hârlău':          { lat: 47.4333, lng: 26.9000, radius: 3000, isSmall: true },
  'Târgu Frumos':    { lat: 47.2000, lng: 27.0000, radius: 3000, isSmall: true },
  // Vâlcea
  'Horezu':          { lat: 45.1036, lng: 23.9903, radius: 3000, isSmall: true },
  'Ocnele Mari':     { lat: 45.0667, lng: 24.2667, radius: 2500, isSmall: true },
  'Brezoi':          { lat: 45.3333, lng: 24.2500, radius: 2500, isSmall: true },
  'Băile Olănești':  { lat: 45.1833, lng: 24.2333, radius: 2500, isSmall: true },
  // Argeș
  'Mioveni':         { lat: 44.9667, lng: 24.9500, radius: 4000, isSmall: true },
  'Costești':        { lat: 44.6667, lng: 24.8833, radius: 3000, isSmall: true },
  'Topoloveni':      { lat: 44.8167, lng: 24.9000, radius: 3000, isSmall: true },
  // Gorj
  'Motru':           { lat: 44.8000, lng: 22.9667, radius: 4000, isSmall: true },
  'Rovinari':        { lat: 44.9167, lng: 23.1667, radius: 3000, isSmall: true },
  'Turceni':         { lat: 44.8667, lng: 23.4000, radius: 3000, isSmall: true },
  // Dâmbovița
  'Pucioasa':        { lat: 44.9333, lng: 25.4333, radius: 4000, isSmall: true },
  'Titu':            { lat: 44.6667, lng: 25.5333, radius: 3000, isSmall: true },
  // Bistrița-Năsăud
  'Năsăud':          { lat: 47.2833, lng: 24.4000, radius: 4000, isSmall: true },
  'Beclean':         { lat: 47.1833, lng: 24.1833, radius: 3000, isSmall: true },
  // Sălaj
  'Șimleu Silvaniei':{ lat: 47.2333, lng: 22.8000, radius: 4000, isSmall: true },
  'Jibou':           { lat: 47.2667, lng: 23.2500, radius: 3000, isSmall: true },
  'Cehu Silvaniei':  { lat: 47.4000, lng: 23.1833, radius: 3000, isSmall: true },
  // Caraș-Severin
  'Caransebeș':      { lat: 45.4167, lng: 22.2167, radius: 5000, isSmall: true },
  'Bocșa':           { lat: 45.3667, lng: 21.7167, radius: 4000, isSmall: true },
  'Moldova Nouă':    { lat: 44.7333, lng: 21.6667, radius: 3000, isSmall: true },
  // Mehedinți
  'Orșova':          { lat: 44.7167, lng: 22.4000, radius: 4000, isSmall: true },
  'Strehaia':        { lat: 44.6167, lng: 23.1833, radius: 3000, isSmall: true },
  // Olt
  'Slatina':         { lat: 44.4333, lng: 24.3667, radius: 7000  },
  'Scornicești':     { lat: 44.5667, lng: 24.5333, radius: 3000, isSmall: true },
  'Balș':            { lat: 44.3500, lng: 24.1000, radius: 4000, isSmall: true },
  // Dolj
  'Băilești':        { lat: 44.0167, lng: 23.3500, radius: 4000, isSmall: true },
  'Calafat':         { lat: 43.9833, lng: 22.9333, radius: 4000, isSmall: true },
  // Teleorman
  'Turnu Măgurele':  { lat: 43.7500, lng: 24.8833, radius: 4000, isSmall: true },
  'Roșiori de Vede': { lat: 44.1167, lng: 24.9833, radius: 4000, isSmall: true },
  // Giurgiu
  'Bolintin-Vale':   { lat: 44.4500, lng: 25.7667, radius: 3000, isSmall: true },
  // Ialomița
  'Urziceni':        { lat: 44.7167, lng: 26.6333, radius: 4000, isSmall: true },
  // Buzău
  'Râmnicu Sărat':   { lat: 45.3833, lng: 27.0500, radius: 5000, isSmall: true },
  'Pogoanele':       { lat: 45.0167, lng: 26.9833, radius: 3000, isSmall: true },
  // Vrancea
  'Adjud':           { lat: 46.1000, lng: 27.1667, radius: 4000, isSmall: true },
  'Mărășești':       { lat: 45.8667, lng: 27.2333, radius: 3000, isSmall: true },
  // Galați
  'Tecuci':          { lat: 45.8500, lng: 27.4167, radius: 5000, isSmall: true },
  'Tg. Bujor':       { lat: 45.8667, lng: 27.9000, radius: 3000, isSmall: true },
  // Tulcea
  'Sulina':          { lat: 45.1500, lng: 29.6833, radius: 2000, isSmall: true },
  'Măcin':           { lat: 45.2500, lng: 28.1333, radius: 3000, isSmall: true },
  'Babadag':         { lat: 44.8833, lng: 28.7167, radius: 3000, isSmall: true },

  // ── 🇭🇺 MAGYARORSZÁG — NAGY VÁROSOK ──────────────────────────────────────
  'Budapest':        { lat: 47.4979, lng: 19.0402, radius: 30000 },
  'Debrecen':        { lat: 47.5316, lng: 21.6273, radius: 15000 },
  'Miskolc':         { lat: 48.1035, lng: 20.7784, radius: 12000 },
  'Pécs':            { lat: 46.0727, lng: 18.2323, radius: 12000 },
  'Győr':            { lat: 47.6875, lng: 17.6504, radius: 12000 },
  'Nyíregyháza':     { lat: 47.9554, lng: 21.7167, radius: 10000 },
  'Kecskemét':       { lat: 46.9061, lng: 19.6909, radius: 10000 },
  'Székesfehérvár':  { lat: 47.1860, lng: 18.4221, radius: 10000 },
  'Szombathely':     { lat: 47.2307, lng: 16.6218, radius: 8000  },
  'Érd':             { lat: 47.3920, lng: 18.9136, radius: 8000  },
  'Tatabánya':       { lat: 47.5853, lng: 18.3953, radius: 8000  },
  'Sopron':          { lat: 47.6849, lng: 16.5845, radius: 8000  },
  'Kaposvár':        { lat: 46.3593, lng: 17.7960, radius: 7000  },
  'Szolnok':         { lat: 47.1781, lng: 20.1826, radius: 8000  },
  'Eger':            { lat: 47.9025, lng: 20.3772, radius: 7000  },
  'Veszprém':        { lat: 47.0930, lng: 17.9086, radius: 7000  },
  'Zalaegerszeg':    { lat: 46.8417, lng: 16.8416, radius: 7000  },
  'Dunaújváros':     { lat: 46.9819, lng: 18.9355, radius: 6000  },
  'Hódmezővásárhely':{ lat: 46.4167, lng: 20.3167, radius: 6000  },
  'Szekszárd':       { lat: 46.3481, lng: 18.7064, radius: 5000  },
  'Békéscsaba':      { lat: 46.6792, lng: 21.0877, radius: 7000  },
  'Salgótarján':     { lat: 48.1000, lng: 19.8000, radius: 6000  },
  'Esztergom':       { lat: 47.7939, lng: 18.7408, radius: 5000  },

  // ── 🇭🇺 MAGYARORSZÁG — KIS VÁROSOK (verseny nélkül) ──────────────────────
  'Gyöngyös':        { lat: 47.7833, lng: 19.9333, radius: 5000, isSmall: true },
  'Hatvan':          { lat: 47.6667, lng: 19.6667, radius: 4000, isSmall: true },
  'Pápa':            { lat: 47.3333, lng: 17.4667, radius: 4000, isSmall: true },
  'Ajka':            { lat: 47.1000, lng: 17.5667, radius: 4000, isSmall: true },
  'Várpalota':       { lat: 47.2000, lng: 18.1333, radius: 3000, isSmall: true },
  'Mosonmagyaróvár': { lat: 47.8667, lng: 17.2667, radius: 5000, isSmall: true },
  'Komárom':         { lat: 47.7333, lng: 18.1167, radius: 4000, isSmall: true },
  'Oroszlány':       { lat: 47.4833, lng: 18.3167, radius: 3000, isSmall: true },
  'Tapolca':         { lat: 46.8833, lng: 17.4333, radius: 3000, isSmall: true },
  'Keszthely':       { lat: 46.7667, lng: 17.2500, radius: 3000, isSmall: true },
  'Balatonfüred':    { lat: 46.9500, lng: 17.8833, radius: 3000, isSmall: true },
  'Siófok':          { lat: 46.9049, lng: 18.0514, radius: 4000, isSmall: true },
  'Balatonalmádi':   { lat: 47.0333, lng: 18.0167, radius: 3000, isSmall: true },
  'Marcali':         { lat: 46.5833, lng: 17.4167, radius: 3000, isSmall: true },
  'Nagykanizsa':     { lat: 46.4536, lng: 16.9914, radius: 6000, isSmall: true },
  'Letenye':         { lat: 46.4333, lng: 16.7000, radius: 2500, isSmall: true },
  'Lenti':           { lat: 46.6167, lng: 16.5333, radius: 2500, isSmall: true },
  'Körmend':         { lat: 47.0167, lng: 16.6000, radius: 3000, isSmall: true },
  'Sárvár':          { lat: 47.2500, lng: 16.9333, radius: 3000, isSmall: true },
  'Celldömölk':      { lat: 47.2500, lng: 17.1500, radius: 3000, isSmall: true },
  'Sárospatak':      { lat: 48.3167, lng: 21.5667, radius: 3000, isSmall: true },
  'Tokaj':           { lat: 48.1167, lng: 21.4167, radius: 2500, isSmall: true },
  'Kisvárda':        { lat: 48.2167, lng: 22.0833, radius: 3000, isSmall: true },
  'Mátészalka':      { lat: 47.9500, lng: 22.3167, radius: 4000, isSmall: true },
  'Fehérgyarmat':    { lat: 47.9833, lng: 22.5167, radius: 3000, isSmall: true },
  'Vásárosnamény':   { lat: 48.1333, lng: 22.3167, radius: 3000, isSmall: true },
  'Berettyóújfalu':  { lat: 47.2167, lng: 21.5500, radius: 3500, isSmall: true },
  'Hajdúböszörmény': { lat: 47.6667, lng: 21.5167, radius: 5000, isSmall: true },
  'Hajdúszoboszló':  { lat: 47.4500, lng: 21.3833, radius: 4000, isSmall: true },
  'Balmazújváros':   { lat: 47.6167, lng: 21.3500, radius: 3000, isSmall: true },
  'Orosháza':        { lat: 46.5667, lng: 20.6667, radius: 4000, isSmall: true },
  'Gyula':           { lat: 46.6500, lng: 21.2833, radius: 4000, isSmall: true },
  'Szarvas':         { lat: 46.8667, lng: 20.5500, radius: 3000, isSmall: true },
  'Makó':            { lat: 46.2167, lng: 20.4833, radius: 4000, isSmall: true },
  'Hőgyész':         { lat: 46.5167, lng: 18.3833, radius: 2500, isSmall: true },
  'Bonyhád':         { lat: 46.3000, lng: 18.5333, radius: 3000, isSmall: true },
  'Mohács':          { lat: 45.9939, lng: 18.6803, radius: 4000, isSmall: true },
  'Baja':            { lat: 46.1833, lng: 18.9500, radius: 5000, isSmall: true },
  'Kiskunfélegyháza':{ lat: 46.7167, lng: 19.8500, radius: 4000, isSmall: true },
  'Kiskunhalas':     { lat: 46.4333, lng: 19.4833, radius: 4000, isSmall: true },
  'Kalocsa':         { lat: 46.5333, lng: 18.9833, radius: 3500, isSmall: true },
  'Jászberény':      { lat: 47.5000, lng: 19.9167, radius: 4500, isSmall: true },
  'Cegléd':          { lat: 47.1667, lng: 19.8000, radius: 4500, isSmall: true },
  'Nagykőrös':       { lat: 47.0333, lng: 19.7833, radius: 3500, isSmall: true },
  'Ózd':             { lat: 48.2167, lng: 20.2833, radius: 5000, isSmall: true },
  'Kazincbarcika':   { lat: 48.2500, lng: 20.6333, radius: 4000, isSmall: true },
  'Szerencs':        { lat: 48.1667, lng: 21.2000, radius: 3000, isSmall: true },
  'Mezőkövesd':      { lat: 47.8167, lng: 20.5833, radius: 3000, isSmall: true },
  'Eger-környék':    { lat: 47.9025, lng: 20.3772, radius: 5000, isSmall: true },
  'Gyönk':           { lat: 46.6333, lng: 18.5500, radius: 2500, isSmall: true },
}

// ── JUDETE — toate cele 41 ──────────────────────────────────────────────────
export const JUDETE: Record<string, string[]> = {
  'Cluj':             ['Cluj-Napoca','Turda','Dej','Câmpia Turzii','Gherla','Huedin','Florești CJ'],
  'Brașov':           ['Brașov','Săcele','Codlea','Zărnești','Râșnov','Predeal','Azuga'],
  'Sibiu':            ['Sibiu','Mediaș','Cisnădie','Avrig','Tălmaciu','Ocna Sibiului'],
  'Mureș':            ['Târgu Mureș','Reghin','Luduș','Sighișoara','Iernut','Sovata'],
  'Alba':             ['Alba Iulia','Sebeș','Blaj','Cugir','Zlatna','Abrud'],
  'Bihor':            ['Oradea','Beiuș','Salonta','Marghita','Aleșd','Valea lui Mihai'],
  'Satu Mare':        ['Satu Mare','Carei','Negrești-Oaș','Tășnad','Ardud'],
  'Maramureș':        ['Baia Mare','Sighetul Marmației','Vișeu de Sus','Borșa','Seini','Câmpulung la Tisa'],
  'Timiș':            ['Timișoara','Lugoj','Deta','Jimbolia','Sânnicolau Mare','Buziaș','Recaș'],
  'Arad':             ['Arad','Ineu','Lipova','Nădlac','Chișineu-Criș','Curtici'],
  'Hunedoara':        ['Deva','Petroșani','Orăștie','Brad','Simeria','Vulcan','Lupeni','Uricani'],
  'Caraș-Severin':    ['Reșița','Caransebeș','Bocșa','Moldova Nouă'],
  'Bistrița-Năsăud':  ['Bistrița','Năsăud','Beclean'],
  'Sălaj':            ['Zalău','Șimleu Silvaniei','Jibou','Cehu Silvaniei'],
  'Prahova':          ['Ploiești','Sinaia','Bușteni','Câmpina','Vălenii de Munte','Băicoi'],
  'Constanța':        ['Constanța','Mangalia','Eforie Nord','Năvodari','Techirghiol','Cernavodă','Ovidiu','Murfatlar'],
  'Iași':             ['Iași','Pașcani','Hârlău','Târgu Frumos'],
  'Suceava':          ['Suceava','Câmpulung Moldovenesc','Rădăuți','Vatra Dornei','Gura Humorului','Fălticeni','Siret'],
  'Neamț':            ['Piatra Neamț','Târgu Neamț','Bicaz','Roznov'],
  'Bacău':            ['Bacău','Onești','Moinești','Comănești','Slănic Moldova'],
  'Vâlcea':           ['Râmnicu Vâlcea','Drăgășani','Horezu','Ocnele Mari','Brezoi','Băile Olănești'],
  'Argeș':            ['Pitești','Curtea de Argeș','Câmpulung','Mioveni','Costești','Topoloveni'],
  'Gorj':             ['Târgu Jiu','Motru','Rovinari','Turceni'],
  'Dâmbovița':        ['Târgoviște','Pucioasa','Titu','Moreni'],
  'Giurgiu':          ['Giurgiu','Bolintin-Vale'],
  'Ialomița':         ['Slobozia','Urziceni','Fetești'],
  'Călărași':         ['Călărași'],
  'Teleorman':        ['Alexandria','Turnu Măgurele','Roșiori de Vede'],
  'Olt':              ['Slatina','Caracal','Scornicești','Balș'],
  'Dolj':             ['Craiova','Băilești','Calafat'],
  'Mehedinți':        ['Drobeta-Turnu Severin','Orșova','Strehaia'],
  'Galați':           ['Galați','Tecuci','Tg. Bujor'],
  'Brăila':           ['Brăila'],
  'Buzău':            ['Buzău','Râmnicu Sărat','Pogoanele'],
  'Vrancea':          ['Focșani','Adjud','Mărășești'],
  'Vaslui':           ['Vaslui','Roman'],
  'Tulcea':           ['Tulcea','Măcin','Babadag','Sulina'],
  'Ilfov/Buc':        ['București'],
  'Sfântu Gheorghe':  ['Sfântu Gheorghe'],
  'Miercurea Ciuc':   ['Miercurea Ciuc'],
}

// ── 🇭🇺 MAGYARORSZÁG MEGYÉI ───────────────────────────────────────────────
export const MEGYEK: Record<string, string[]> = {
  'Budapest':           ['Budapest'],
  'Pest megye':         ['Érd','Cegléd','Nagykőrös','Jászberény','Hatvan'],
  'Győr-Moson-Sopron':  ['Győr','Sopron','Mosonmagyaróvár','Komárom'],
  'Fejér':              ['Székesfehérvár','Dunaújváros','Érд','Várpalota'],
  'Veszprém':           ['Veszprém','Ajka','Pápa','Balatonfüred','Balatonalmádi','Tapolca'],
  'Zala':               ['Zalaegerszeg','Nagykanizsa','Keszthely','Lenti','Körmend'],
  'Somogy':             ['Kaposvár','Siófok','Marcali'],
  'Tolna':              ['Szekszárd','Bonyhád','Mohács'],
  'Baranya':            ['Pécs','Mohács','Baja'],
  'Bács-Kiskun':        ['Kecskemét','Baja','Kiskunfélegyháza','Kiskunhalas','Kalocsa'],
  'Csongrád-Csanád':    ['Hódmezővásárhely','Makó','Orosháza'],
  'Békés':              ['Békéscsaba','Gyula','Orosháza','Szarvas'],
  'Hajdú-Bihar':        ['Debrecen','Hajdúböszörmény','Hajdúszoboszló','Balmazújváros','Berettyóújfalu'],
  'Jász-Nagykun-Szolnok':['Szolnok','Jászberény'],
  'Heves':              ['Eger','Gyöngyös'],
  'Nógrád':             ['Salgótarján'],
  'Borsod-Abaúj-Zemplén':['Miskolc','Ózd','Kazincbarcika','Szerencs','Mezőkövesd','Sárospatak','Tokaj'],
  'Szabolcs-Szatmár-Bereg':['Nyíregyháza','Kisvárda','Mátészalka','Fehérgyarmat','Vásárosnamény'],
  'Vas':                ['Szombathely','Körmend','Sárvár','Celldömölk'],
  'Komárom-Esztergom':  ['Tatabánya','Esztergom','Komárom','Oroszlány'],
}

// ── CATEGORII — extinse masiv ─────────────────────────────────────────────
export const BUSINESS_CATEGORIES: Record<string, string> = {
  // Cazare
  lodging:              'Hotel / Pensiune / Motel',
  campground:           'Camping / Cabană / Vilă',
  rv_park:              'Cabană / Sat de Vacanță',

  // Beauty & Wellness
  beauty_salon:         'Salon de Înfrumusețare',
  hair_care:            'Frizerie / Coafor',
  spa:                  'Spa / Salon Masaj',
  nail_salon:           'Salon Unghii / Nail Art',

  // Alimentație
  restaurant:           'Restaurant / Cafenea',
  cafe:                 'Cafenea / Coffee Shop',
  bar:                  'Bar / Pub / Club',
  bakery:               'Brutărie / Patiserie / Cofetărie',
  meal_takeaway:        'Livrare Mâncare / Fast-Food',

  // Auto — complet
  car_repair:           'Service Auto / Mecanică',
  car_wash:             'Spălătorie Auto',
  car_dealer:           'Dealer Auto / Mașini Noi',
  used_car_dealer:      'Parc Auto / Mașini Second-Hand',
  gas_station:          'Vulcanizare / Anvelope',
  car_rental:           'Rent-a-Car / Închirieri Auto',
  car_parts:            'Piese Auto / Accesorii',
  towing_service:       'Tractări Auto / Asistență Rutieră',
  auto_body:            'Tinichigerie / Vopsitorie Auto',
  auto_electrical:      'Electrificare / Geamuri Auto',
  motorcycle_dealer:    'Dealer Moto / ATV / Scutere',

  // Medical & Sănătate
  dentist:              'Cabinet Stomatologic',
  doctor:               'Cabinet Medical / Policlinică',
  physiotherapist:      'Cabinet Fizioterapie / Kinetoterapie',
  veterinary_care:      'Cabinet Veterinar',
  pharmacy:             'Farmacie / Optică Medicală',

  // Fitness & Sport
  gym:                  'Sală de Fitness / Sport',
  bowling_alley:        'Bowling / Paintball / Karting',
  stadium:              'Club Sportiv / Teren Sport',

  // Servicii profesionale
  lawyer:               'Cabinet Avocat',
  accounting:           'Contabilitate / Firmă Consultanță',
  real_estate_agency:   'Agenție Imobiliară',
  insurance_agency:     'Agenție Asigurări',
  travel_agency:        'Agenție de Turism',

  // Meșteșuguri & Construcții
  painter:              'Constructor / Zugrav / Renovări',
  plumber:              'Instalator / Sanitare',
  electrician:          'Electrician / Automatizări',
  roofing_contractor:   'Acoperișuri / Tâmplărie',

  // Servicii diverse
  florist:              'Florărie',
  photographer:         'Studio Foto / Video',
  moving_company:       'Firmă Mutări / Transport',
  laundry:              'Curățătorie / Spălătorie Haine',
  storage:              'Depozitare / Self-Storage',
  funeral_home:         'Servicii Funerare',
  driving_school:       'Școală Auto',
  event_venue:          'Sală Evenimente / Nunți',
  pet_store:            'Magazin Animale / Pet Shop',
  book_store:           'Librărie / Papetărie',
  furniture_store:      'Mobilă / Design Interior',
  clothing_store:       'Magazin Haine / Boutique',
  shoe_store:           'Magazin Încălțăminte',
  jewelry_store:        'Bijuterii / Ceasuri',
  electronics_store:    'Electronice / GSM / IT',
}

// ── CATEGORII CONVERSIE MAXIMĂ ───────────────────────────────────────────
export const HIGH_CONVERSION_CATEGORIES = [
  'beauty_salon', 'lodging', 'campground', 'hair_care', 'bakery',
  'car_repair', 'dentist', 'photographer', 'restaurant', 'spa',
  'event_venue', 'florist', 'physiotherapist', 'gym',
]

// ── PAIN POINTS per categorie ─────────────────────────────────────────────
export interface PainPoint {
  pain: string; gain: string; hook: string; urgency: string; waHook: string;
}

export const CATEGORY_PAIN_POINTS: Record<string, PainPoint> = {
  lodging: {
    pain: 'turiștii rezervă pe Booking.com și plătiți 15-20% comision – un site propriu vă scapă de asta',
    gain: 'rezervări directe fără comision, galerie foto profesională, pachete speciale',
    hook: 'un site propriu vă economisește mii de RON pe lună față de Booking.com',
    urgency: 'sezonul estival se apropie – turiștii rezervă vacanțele chiar acum',
    waHook: 'rezervări directe fără comision Booking.com',
  },
  campground: {
    pain: 'turiștii nu vă găsesc online și merg la cabane și campinguri cu site',
    gain: 'rezervări online directe, prezentare locație, pachete speciale weekend',
    hook: 'căutările pentru cabane și campinguri sunt la maxim în primăvară și vară',
    urgency: 'sezonul turistic începe în Mai – acum e momentul să apăreți pe Google',
    waHook: 'rezervări directe pentru weekend-uri și vacanțe',
  },
  rv_park: {
    pain: 'turiștii caută cazare în natură online – fără site pierdeți rezervări în fiecare zi',
    gain: 'vizibilitate online, rezervări directe, galerie cu locația',
    hook: 'turismul rural și ecoturismul sunt în plină expansiune în România',
    urgency: 'vara se apropie – rezervările se fac acum',
    waHook: 'rezervări online pentru cazare în natură',
  },
  beauty_salon: {
    pain: 'clienții vă caută pe Instagram dar nu găsesc prețurile sau cum să rezerve',
    gain: 'programări online, galerie foto cu lucrările, mai puține telefoane',
    hook: 'femeile caută saloane pe Google, nu în cartea de telefoane',
    urgency: 'salonul din vecinătate are deja site și apare primul în căutări',
    waHook: 'rezervări online fără telefoane și clienți noi zilnic',
  },
  hair_care: {
    pain: 'clienții vin la recomandare, dar rata de clienți noi e mică fără prezență online',
    gain: 'rezervări online, galerie cu stiluri, fidelizare clienți existenți',
    hook: 'salonul cu site apare în top 3 Google Maps când cineva caută coafor în zona ta',
    urgency: 'poziția în Google se construiește în timp – cu cât începi mai devreme, cu atât ești mai sus',
    waHook: 'rezervări online și clienți noi',
  },
  spa: {
    pain: 'clienții caută spa și masaj pe Google – fără site ești invizibil pentru ei',
    gain: 'rezervări online 24/7, meniu de servicii cu prețuri, pachete cadou',
    hook: 'cererea pentru servicii de relaxare și wellness a crescut cu 60% post-pandemic',
    urgency: 'de 8 Martie și 1 Iunie oamenii caută cadouri spa – fii găsit',
    waHook: 'rezervări online și pachete cadou',
  },
  nail_salon: {
    pain: 'clienții caută nail art pe Instagram dar nu știu cum să rezerve sau unde ești',
    gain: 'programări online, galerie cu lucrări, locație pe Google Maps',
    hook: 'căutările pentru nail art și unghii gel au explodat în ultimii 2 ani',
    urgency: 'înainte de Paști și vară cererea crește – fii pregătit',
    waHook: 'programări online și galerie de lucrări',
  },
  restaurant: {
    pain: 'clienții nu vă pot vedea meniul online și nu pot rezerva o masă',
    gain: 'rezervări online, meniu digital, prezență pe Google și TripAdvisor',
    hook: '72% din oameni caută restaurante online înainte să iasă din casă',
    urgency: 'restaurantele cu site primesc cu 40% mai multe rezervări în weekend',
    waHook: 'clienți noi care vă caută online',
  },
  cafe: {
    pain: 'clienții caută cafenele pe Google Maps – fără site și ore de funcționare, îi pierzi',
    gain: 'apariție pe Google Maps, menu digital, story-uri și evenimente promovate',
    hook: 'cultura coffee shop a explodat – oamenii caută online locul perfect',
    urgency: 'primăvara și terasa de vară aduc clienți – fii găsit acum',
    waHook: 'clienți noi care caută cafenea în zona ta',
  },
  bar: {
    pain: 'fără site nu apăreți în căutări când cineva caută unde să iasă în seară asta',
    gain: 'pagină cu evenimente, meniu, rezervări pentru grupuri, apariție pe Google',
    hook: 'căutările pentru "bar [oraș]" și "club [oraș]" sunt la maxim în weekend',
    urgency: 'concurența cu site apare prima în Google – tu nu apari deloc',
    waHook: 'rezervări de grup și evenimente promovate online',
  },
  bakery: {
    pain: 'comenzile de tort se fac tot mai mult online, nu telefonic',
    gain: 'comenzi torturi aniversare și evenimente, catalog produse, program vizibil',
    hook: 'căutările pentru "tort comandă [oraș]" cresc continuu',
    urgency: 'comenzile de Paști vin acum – fii vizibil când lumea caută',
    waHook: 'comenzi torturi și produse online de Paști',
  },
  meal_takeaway: {
    pain: 'fără site propriu plătiți comision mare pe Glovo/Tazz pentru fiecare comandă',
    gain: 'comenzi directe fără comision, meniu online, program livrare vizibil',
    hook: 'un site de comenzi propriu elimină comisioanele de 20-30% per comandă',
    urgency: 'fiecare lună fără site propriu = mii de RON în comisioane pierdute',
    waHook: 'comenzi directe fără comision Glovo sau Tazz',
  },
  car_repair: {
    pain: 'când mașina se strică, oamenii caută urgent pe Google – dacă nu ești acolo, mergi la concurență',
    gain: 'clienți noi din Google, lista de servicii și prețuri, credibilitate',
    hook: '"service auto [orașul tău]" e căutat de mii de ori pe lună',
    urgency: 'service-urile cu site apar primele în Google Maps și primesc 3x mai multe apeluri',
    waHook: 'să apăreați primii pe Google când cineva caută service',
  },
  car_wash: {
    pain: 'clienții caută spălătorie pe Google Maps când sunt în zonă',
    gain: 'vizibilitate pe Google Maps, servicii și prețuri afișate, recenzii',
    hook: '"spălătorie auto [oraș]" e căutat zilnic de sute de ori',
    urgency: 'primăvara = vârf de sezon – clienții caută chiar acum',
    waHook: 'clienți noi care caută spălătorie pe Google',
  },
  car_dealer: {
    pain: 'cumpărătorii de mașini noi caută online înainte să viziteze orice dealer',
    gain: 'galerie modele online, prețuri și contacte, credibilitate față de concurență',
    hook: '90% din cumpărătorii de mașini caută online înainte să meargă la dealer',
    urgency: 'un site profesional vă diferențiază imediat față de concurența fără prezență web',
    waHook: 'clienți noi care caută mașina ta online',
  },
  used_car_dealer: {
    pain: 'parcul vostru auto apare pe OLX și Autovit, dar nu aveți site propriu – pierdeți credibilitate',
    gain: 'galerie stoc actualizat, prețuri, rate și contacte – totul pe site-ul vostru',
    hook: 'parcurile auto cu site propriu sunt percepute ca mai serioase și vând mai rapid',
    urgency: 'fiecare mașină vândută prin OLX înseamnă comision plătit – site-ul propriu elimină asta',
    waHook: 'clienți noi care caută mașini second-hand direct la voi',
  },
  gas_station: {
    pain: 'clienții caută vulcanizare urgentă pe Google – fără site ești invizibil',
    gain: 'apariție în Google Maps, servicii și program vizibil, recenzii',
    hook: '"vulcanizare urgentă [oraș]" are sute de căutări zilnic',
    urgency: 'schimbul de anvelope de sezon e acum – fii găsit',
    waHook: 'clienți urgentați care caută vulcanizare pe Google',
  },
  car_rental: {
    pain: 'clienții caută rent-a-car pe Google și rezervă online – fără site pierdeți rezervări zilnic',
    gain: 'rezervări online directe, flotă vizibilă cu prețuri, credibilitate față de platformele mari',
    hook: 'turismul și business travel-ul cresc – cererea de rent-a-car e la maxim vara',
    urgency: 'sezonul estival se apropie – fii găsit înainte ca turiștii să rezerve la concurență',
    waHook: 'rezervări directe fără comision Booking sau alte platforme',
  },
  car_parts: {
    pain: 'mecanicii și șoferii caută piese auto online – fără site nu apăreți în niciun rezultat',
    gain: 'catalog piese cu disponibilitate, prețuri, contacte rapide – clienți din toată zona',
    hook: '"piese auto [marcă] [oraș]" are mii de căutări lunare',
    urgency: 'concurența online în piese auto crește – fii prezent înainte să fie prea târziu',
    waHook: 'clienți care caută piese auto direct la voi pe Google',
  },
  towing_service: {
    pain: 'când mașina rămâne în pană, oamenii caută tractare pe Google în urgență – ești acolo?',
    gain: 'apariție urgentă pe Google Maps, număr de contact vizibil, recenzii de încredere',
    hook: '"tractare auto urgentă [oraș]" e căutată de zeci de ori pe zi',
    urgency: 'fiecare zi fără site = clienți urgentați care merg la concurența care apare pe Google',
    waHook: 'apeluri urgente de tractare – să fii primul pe Google',
  },
  auto_body: {
    pain: 'după un accident, oamenii caută tinichigerie pe Google – fără site ești invizibil',
    gain: 'portofoliu cu lucrări înainte/după, servicii și prețuri, credibilitate',
    hook: '"tinichigerie vopsitorie [oraș]" are sute de căutări lunare',
    urgency: 'sezonul accidentelor de iarnă a trecut – acum vin reparațiile estetice de primăvară',
    waHook: 'clienți care caută tinichigerie și vopsitorie de calitate',
  },
  auto_electrical: {
    pain: 'problemele electrice la mașini se caută urgent pe Google – fără site ești invizibil',
    gain: 'apariție în Google Maps, servicii specializate vizibile, credibilitate',
    hook: 'electrica auto și instalarea de geamuri sunt servicii tot mai căutate online',
    urgency: 'mașinile electrice și hibride cresc – cererea pentru electricieni auto e în boom',
    waHook: 'clienți care caută electrician auto sau geamuri în zona ta',
  },
  motorcycle_dealer: {
    pain: 'motocicliștii caută moto și ATV-uri online – fără site nu existați pentru ei',
    gain: 'galerie modele, prețuri, echipamente și accesorii – totul pe site-ul vostru',
    hook: 'vânzările de motociclete și ATV-uri au crescut cu 40% în ultimii 3 ani în România',
    urgency: 'sezonul moto începe în Aprilie – cumpărătorii caută chiar acum',
    waHook: 'clienți noi care caută moto, ATV sau scutere online',
  },
  dentist: {
    pain: 'pacienții noi nu vă găsesc și merg la concurența care are site modern',
    gain: 'programări online 24/7, imagine profesională, pacienți noi lunar',
    hook: '85% din pacienți verifică online înainte să aleagă un stomatolog',
    urgency: 'cabinetele cu site primesc 8-12 programări noi pe lună din online',
    waHook: 'pacienți noi din Google în fiecare lună',
  },
  doctor: {
    pain: 'pacienții noi nu știu ce specialități oferi, programul sau cum te contactezi',
    gain: 'programări online, lista de servicii, credibilitate și încredere',
    hook: '90% din pacienți caută online informații despre medic înainte de prima vizită',
    urgency: 'cabinetele cu site profesional sunt percepute ca mai competente',
    waHook: 'programări online și pacienți noi lunar',
  },
  physiotherapist: {
    pain: 'pacienții caută fizioterapeut pe Google după recomandarea medicului',
    gain: 'programări online, lista de servicii și prețuri, credibilitate',
    hook: 'cererea pentru fizioterapie a crescut cu 40% post-pandemic',
    urgency: 'cabinetele cu site sunt pline – cele fără site au locuri libere',
    waHook: 'programări online și pacienți noi',
  },
  veterinary_care: {
    pain: 'proprietarii de animale caută veterinar pe Google când e urgență',
    gain: 'programări online, urgențe 24/7, clienți noi fideli',
    hook: 'numărul de animale de companie din România a crescut cu 30% în ultimii 3 ani',
    urgency: 'clinicile veterinare cu site primesc 3x mai multe programări noi',
    waHook: 'programări online și clienți noi urgent',
  },
  pharmacy: {
    pain: 'clienții caută farmacie de gardă sau produse specifice online',
    gain: 'program vizibil, produse disponibile, apariție în Google Maps',
    hook: 'căutările pentru farmacii de gardă și produse OTC sunt în creștere',
    urgency: 'concurența online a farmaciilor crește – fii prezent înainte',
    waHook: 'clienți noi care caută farmacie în zona ta',
  },
  gym: {
    pain: 'oamenii caută săli de sport pe Google – fără site merg la sala de alături',
    gain: 'abonamente online, program clase, galerie echipamente',
    hook: 'căutările pentru săli de sport sunt la maxim tot sezonul',
    urgency: 'fiecare zi fără site e o zi cu abonamente pierdute',
    waHook: 'abonamente noi și vizibilitate online',
  },
  bowling_alley: {
    pain: 'grupurile caută activități de petrecere a timpului liber online – fără site nu te găsesc',
    gain: 'rezervări online pentru grupuri, tarife și orare vizibile, pachete birthday',
    hook: 'petrecerile corporate și de grup se rezervă exclusiv online',
    urgency: 'weekendurile sunt pline pentru locurile cu site – tu pierzi rezervări',
    waHook: 'rezervări online pentru grupuri și evenimente',
  },
  lawyer: {
    pain: 'clienții caută avocați pe Google, nu din gură în gură',
    gain: 'consultanță online, credibilitate profesională, clienți noi',
    hook: '68% din români caută avocați online înainte de primul contact',
    urgency: 'cabinetele cu site obțin 5-10 consultanțe noi pe lună din online',
    waHook: 'clienți noi care caută avocat online',
  },
  accounting: {
    pain: 'firmele tinere caută contabili pe Google – fără site nu existați pentru ele',
    gain: 'clienți noi lunar, imagine profesională, formulare de contact',
    hook: 'startup-urile și firmele noi își caută contabilul exclusiv online',
    urgency: 'sezonul declarațiilor e acum – firmele caută contabili chiar acum',
    waHook: 'firme noi care caută contabil pe Google',
  },
  real_estate_agency: {
    pain: 'clienții caută proprietăți pe site-uri specializate – fără prezență proprie pierdeți credibilitate',
    gain: 'portofoliu de proprietăți, formulare contact, credibilitate față de agențiile mari',
    hook: '95% din căutările imobiliare încep online',
    urgency: 'piața imobiliară e activă – cumpărătorii caută zilnic',
    waHook: 'clienți noi care caută proprietăți prin agenție',
  },
  travel_agency: {
    pain: 'turiștii caută pachete online – fără site pierdeți în fața agențiilor cu prezență web',
    gain: 'catalog de pachete, cereri de ofertă online, credibilitate',
    hook: 'booking-urile online pentru vacanțe sunt la maxim în primăvară',
    urgency: 'vacanțele de vară se rezervă acum – fii găsit',
    waHook: 'cereri de ofertă pentru vacanțe online',
  },
  painter: {
    pain: 'constructorii și zugravii fără site pierd contracte mari de renovare',
    gain: 'portofoliu lucrări, cereri de ofertă online, credibilitate',
    hook: '"zugrav [oraș]" are mii de căutări lunar pe Google',
    urgency: 'sezonul construcțiilor e acum – fiecare săptămână fără site = bani pierduți',
    waHook: 'cereri de ofertă online pentru renovări',
  },
  plumber: {
    pain: 'când țevile se sparg la ora 10 noaptea, clientul caută pe Google – nu în agendă',
    gain: 'apeluri urgente non-stop, zonă de acoperire clară, recenzii verificate',
    hook: '"instalator urgență [oraș]" e una din cele mai căutate fraze locale',
    urgency: 'instalatorii cu site sunt contactați de 4x mai mulți clienți noi lunar',
    waHook: 'apeluri urgente din Google când cineva caută instalator',
  },
  electrician: {
    pain: 'clienții nu știu ce servicii oferi, la ce prețuri și dacă ești disponibil',
    gain: 'lead-uri noi zilnic, portofoliu de lucrări, zonă de activitate vizibilă',
    hook: 'căutările pentru electricieni locali au crescut cu 60% în ultimii 2 ani',
    urgency: 'fără site ești invizibil pentru 90% din clienții potențiali',
    waHook: 'clienți noi din zona voastră prin Google',
  },
  roofing_contractor: {
    pain: 'lucrările de acoperiș se caută pe Google – fără portofoliu online pierzi contracte',
    gain: 'portofoliu lucrări cu poze, cereri de ofertă, credibilitate față de firme mari',
    hook: 'renovările și construcțiile noi sunt în creștere – clienții caută meșteri online',
    urgency: 'sezonul bun de construcții e Mai–Septembrie – rezervă-ți clienții acum',
    waHook: 'cereri de ofertă pentru acoperișuri și tâmplărie',
  },
  florist: {
    pain: 'de Paști și nunți, oamenii comandă flori online – ești acolo?',
    gain: 'comenzi online, catalog produse, livrare în oraș',
    hook: 'florile sunt unul din cele mai cumpărate cadouri online',
    urgency: 'Paștele și sezonul nunților aduc cel mai mult trafic online',
    waHook: 'comenzi online pentru nunți și ocazii',
  },
  photographer: {
    pain: 'mirii caută fotograf online – fără portofoliu web pierzi contracte',
    gain: 'portofoliu online 24/7, cereri de la mirei, pachete și prețuri vizibile',
    hook: 'sezonul de nunți 2026 e la maxim – mirii rezervă cu 6-12 luni înainte',
    urgency: 'fiecare nuntă pierdută = 1000-3000 EUR lăsați pe masă',
    waHook: 'portofoliu online și cereri de la mirei',
  },
  moving_company: {
    pain: 'clienții caută firmă de mutări urgent pe Google – fără site ești invizibil',
    gain: 'cereri de ofertă online din zonă, lista de servicii, credibilitate',
    hook: 'mutările sunt planificate online în 80% din cazuri',
    urgency: 'primăvara și vara = vârf de sezon pentru mutări',
    waHook: 'cereri de ofertă online din zona voastră',
  },
  laundry: {
    pain: 'clienții caută curățătorie pe Google Maps – fără apariție online pierzi clienți',
    gain: 'apariție pe Google Maps, lista de servicii, prețuri și timp de livrare vizibile',
    hook: 'căutările pentru curățătorie haine și perdele cresc constant',
    urgency: 'primăvara = sezon de curățenie generală – clienții caută acum',
    waHook: 'clienți noi care caută curățătorie în zona ta',
  },
  driving_school: {
    pain: 'tinerii caută școli auto pe Google și pe recomandări online',
    gain: 'programare la înmatriculare online, prețuri transparente, recenzii',
    hook: 'căutările pentru "școală auto [oraș]" sunt constante tot anul',
    urgency: 'sesiunile de vară sunt cele mai aglomerate – înscrie-te înainte să se umple',
    waHook: 'cursanți noi care caută școală auto online',
  },
  event_venue: {
    pain: 'nunțile și evenimentele se planifică online – fără site nu ești în shortlist',
    gain: 'formulare cerere de ofertă, galerie sală, pachete all-inclusive vizibile',
    hook: 'mirii vizitează în medie 5-7 locații găsite online înainte să decidă',
    urgency: 'nunțile din vară 2026 se rezervă acum – fii în lista lor',
    waHook: 'cereri de ofertă pentru nunți și evenimente',
  },
  pet_store: {
    pain: 'proprietarii de animale caută produse și sfaturi online înainte să cumpere',
    gain: 'catalog produse, servicii grooming, programări veterinare asociate',
    hook: 'piața de pet supplies din România a crescut cu 35% în 3 ani',
    urgency: 'concurența online e mare – fii găsit înainte ca clientul să comande de pe Amazon',
    waHook: 'clienți noi care caută produse pentru animale în zona ta',
  },
  furniture_store: {
    pain: 'clienții caută mobilă online înainte să viziteze orice showroom fizic',
    gain: 'catalog cu produse și prețuri, galerie amenajări, cereri de ofertă',
    hook: 'peste 70% din cumpărătorii de mobilă caută online înainte de achiziție',
    urgency: 'mutările de primăvară aduc cerere de mobilă nouă – fii găsit',
    waHook: 'clienți noi care caută mobilă sau amenajări online',
  },
  clothing_store: {
    pain: 'fără prezență online pierzi clienți față de magazinele online și rețelele mari',
    gain: 'catalog cu colecțiile noi, program și locație, diferențierea față de online',
    hook: 'clienții fideli caută magazinele preferate pe Google pentru orar și noutăți',
    urgency: 'colecțiile de primăvară sunt acum – anunță-le online',
    waHook: 'clienți fideli și noi atrași prin prezență online',
  },
  default: {
    pain: 'clienții potențiali nu vă pot găsi online și merg la concurența care are prezență web',
    gain: 'vizibilitate online 24/7, clienți noi în fiecare lună, imagine profesională',
    hook: '97% din consumatori caută servicii locale pe internet înainte să cumpere',
    urgency: 'fiecare zi fără website e o zi în care clienții merg la concurența ta',
    waHook: 'clienți noi din Google zilnic',
  },
}

// ── 🇭🇺 MAGYAR VÁROSOK LISTÁJA (city search-hez) ─────────────────────────
export const HU_CITIES = [
  'Budapest','Debrecen','Miskolc','Pécs','Győr','Nyíregyháza','Kecskemét',
  'Székesfehérvár','Szombathely','Érd','Tatabánya','Sopron','Kaposvár',
  'Szolnok','Eger','Veszprém','Zalaegerszeg','Dunaújváros','Hódmezővásárhely',
  'Szekszárd','Békéscsaba','Salgótarján','Esztergom','Gyöngyös','Hatvan',
  'Pápa','Ajka','Várpalota','Mosonmagyaróvár','Komárom','Oroszlány','Tapolca',
  'Keszthely','Balatonfüred','Siófok','Balatonalmádi','Marcali','Nagykanizsa',
  'Körmend','Sárvár','Celldömölk','Sárospatak','Tokaj','Kisvárda','Mátészalka',
  'Fehérgyarmat','Vásárosnamény','Berettyóújfalu','Hajdúböszörmény','Hajdúszoboszló',
  'Balmazújváros','Orosháza','Gyula','Szarvas','Makó','Bonyhád','Mohács','Baja',
  'Kiskunfélegyháza','Kiskunhalas','Kalocsa','Jászberény','Cegléd','Nagykőrös',
  'Ózd','Kazincbarcika','Szerencs','Mezőkövesd',
]

// ── DETECT LANGUAGE: magyar városok = HU, román városok = RO ─────────────
export function detectLanguage(city: string): 'hu' | 'ro' {
  return HU_CITIES.includes(city) ? 'hu' : 'ro'
}

// ── 🇭🇺 MAGYAR PAIN POINTS (WhatsApp üzenetekhez) ────────────────────────
export const HU_PAIN_POINTS: Record<string, PainPoint> = {
  beauty_salon: {
    pain: 'az ügyfelek keresik Önt online, de nincs weboldaluk, ahol időpontot foglalhatnak',
    gain: 'online időpontfoglalás, fotógaléria a munkákról, új ügyfelek Google-ről',
    hook: 'a nők Google-on keresnek szalonokat, nem telefonkönyvben',
    urgency: 'a szomszéd szalon már van weboldala és előbb jelenik meg a keresőkben',
    waHook: 'online foglalás és új ügyfelek minden nap',
  },
  hair_care: {
    pain: 'az ügyfelek ajánlás alapján jönnek, de az online jelenlét nélkül kevés az új ügyfél',
    gain: 'online foglalás, stílus galéria, meglévő ügyfelek megtartása',
    hook: 'a weboldallal rendelkező fodrász az első 3-ban jelenik meg Google Maps-en',
    urgency: 'a Google pozíció időbe telik – minél előbb kezdi, annál magasabban áll',
    waHook: 'online foglalás és új ügyfelek',
  },
  restaurant: {
    pain: 'az ügyfelek nem tudják megnézni az étlapot és nem tudnak asztalt foglalni online',
    gain: 'online asztalfoglalás, digitális étlap, megjelenés a Google-n és TripAdvisoron',
    hook: 'az emberek 72%-a online keres éttermet mielőtt elmegy',
    urgency: 'a weboldallal rendelkező éttermek 40%-kal több hétvégi foglalást kapnak',
    waHook: 'új ügyfelek akik online keresnek éttermet',
  },
  lodging: {
    pain: 'a vendégek a Booking.com-on foglalnak és 15-20% jutalékot fizetnek – saját weboldal megszünteti ezt',
    gain: 'közvetlen foglalások jutalék nélkül, profi fotógaléria, különleges csomagok',
    hook: 'saját weboldal havonta több ezer forintot takarít meg a jutalékokon',
    urgency: 'a nyári szezon közeleg – a turisták most foglalják a nyaralásokat',
    waHook: 'közvetlen foglalások Booking.com jutalék nélkül',
  },
  campground: {
    pain: 'a turisták nem találják online, és weboldallal rendelkező szálláshelyekhez mennek',
    gain: 'közvetlen online foglalás, helyszínbemutató, hétvégi különleges ajánlatok',
    hook: 'a faházak és kempingek keresése tavasszal és nyáron a csúcson van',
    urgency: 'a turisztikai szezon május-ban indul – most kell felkerülni a Google-ra',
    waHook: 'közvetlen foglalások hétvégékre és nyaralásokra',
  },
  dentist: {
    pain: 'az új betegek nem találják és a konkurenciához mennek akinek van modern weboldala',
    gain: '24/7 online időpontfoglalás, professzionális imázs, havonta új betegek',
    hook: 'a betegek 85%-a online keres fogorvost mielőtt választ',
    urgency: 'a weboldallal rendelkező rendelők havonta 8-12 új beteget kapnak online-ból',
    waHook: 'új betegek Google-ről minden hónapban',
  },
  doctor: {
    pain: 'az új betegek nem tudják mit kínál, mikor rendel és hogyan jelentkezzenek',
    gain: 'online bejelentkezés, szolgáltatáslista, bizalom és hitelesség',
    hook: 'a betegek 90%-a online keres információt az orvosról az első látogatás előtt',
    urgency: 'a weboldallal rendelkező rendelők professzionálisabbnak tűnnek',
    waHook: 'online bejelentkezés és új betegek havonta',
  },
  car_repair: {
    pain: 'amikor a kocsi elromlik, az emberek Google-on keresnek – ha nincs ott, a konkurenciához mennek',
    gain: 'új ügyfelek Google-ről, szolgáltatáslista árakkal, hitelességsség',
    hook: '"autószerelő [város]" havonta ezreket keres a Google-on',
    urgency: 'a weboldallal rendelkező szerelők az első helyen jelennek meg és 3x több hívást kapnak',
    waHook: 'hogy elsőként jelenjenek meg amikor valaki szerelőt keres',
  },
  used_car_dealer: {
    pain: 'a használt autó piac az interneten van – weboldal nélkül elveszíti a hitelességét',
    gain: 'online autókínálat frissített készlettel, árak, részletek és kapcsolat',
    hook: 'saját weboldallal rendelkező autókereskedők megbízhatóbbnak tűnnek mint az OLX hirdetők',
    urgency: 'minden OLX-en keresztül eladott autó jutalékot jelent – saját weboldal ezt megszünteti',
    waHook: 'új ügyfelek akik online keresnek használt autót',
  },
  car_wash: {
    pain: 'az ügyfelek Google Maps-en keresnek autómosót a közelükben',
    gain: 'megjelenés a Google Maps-en, szolgáltatások és árak, vélemények',
    hook: '"autómosó [város]" naponta százszor keresnek rá',
    urgency: 'tavasz = csúcsszezon – az ügyfelek most keresnek',
    waHook: 'új ügyfelek akik autómosót keresnek Google-n',
  },
  bakery: {
    pain: 'a torta rendelések egyre inkább online zajlanak, nem telefonon',
    gain: 'torta és sütemény rendelések online, termékkatalógus, látható nyitvatartás',
    hook: 'a "[város] torta rendelés" keresések folyamatosan nőnek',
    urgency: 'húsvéti rendelések most jönnek – legyen ott amikor keresik',
    waHook: 'online torta és termék rendelések húsvétra',
  },
  gym: {
    pain: 'az emberek Google-on keresnek edzőtermet – weboldal nélkül a szomszédhoz mennek',
    gain: 'online bérlet vásárlás, órarend, felszerelés galéria',
    hook: 'az edzőterem keresések egész évben a csúcson vannak',
    urgency: 'minden weboldal nélküli nap elveszített bérlet',
    waHook: 'új tagok és online láthatóság',
  },
  florist: {
    pain: 'húsvétkor és esküvőkre az emberek online rendelnek virágot – ott van?',
    gain: 'online rendelések, termékkatalógus, városon belüli szállítás',
    hook: 'a virág az egyik legtöbbet online vásárolt ajándék',
    urgency: 'húsvét és az esküvői szezon hozza a legtöbb online forgalmat',
    waHook: 'online rendelések esküvőkre és alkalmakra',
  },
  photographer: {
    pain: 'a párok online keresnek fotóst – portfólió weboldal nélkül elveszíti a megrendeléseket',
    gain: '24/7 online portfólió, érdeklődők a menyasszonyoktól, csomagok és árak láthatóan',
    hook: 'a 2026-os esküvői szezon tele van – a párok 6-12 hónappal előre foglalnak',
    urgency: 'minden elveszített esküvő 400.000-1.200.000 Ft bevételkiesés',
    waHook: 'online portfólió és érdeklődők menyasszonyoktól',
  },
  event_venue: {
    pain: 'az esküvők és rendezvények online terveződnek – weboldal nélkül nem kerül a listára',
    gain: 'ajánlatkérő űrlap, teremgaléria, all-inclusive csomagok láthatóan',
    hook: 'a párok átlagosan 5-7 helyszínt néznek meg online mielőtt döntenek',
    urgency: 'a 2026-os nyári esküvőket most foglalják – legyen rajta a listán',
    waHook: 'ajánlatkérések esküvőkre és rendezvényekre',
  },
  spa: {
    pain: 'az ügyfelek Google-on keresnek spa és masszázs szalonokat',
    gain: '24/7 online időpontfoglalás, szolgáltatásmenü árakkal, ajándékutalványok',
    hook: 'a wellness és relaxációs keresések 60%-kal nőttek a pandémia után',
    urgency: 'anyák napján és nőnapon az emberek spa ajándékot keresnek – legyen megtalálható',
    waHook: 'online foglalások és ajándékutalványok',
  },
  nail_salon: {
    pain: 'az ügyfelek Instagramon keresik a nail artet, de nem tudnak foglalni',
    gain: 'online foglalás, munkagaléria, Google Maps megjelenés',
    hook: 'a nail art és gél köröm keresések az elmúlt 2 évben felrobbantak',
    urgency: 'húsvét és nyár előtt a kereslet csúcson van – legyen felkészülve',
    waHook: 'online foglalások és munkagaléria',
  },
  lawyer: {
    pain: 'az ügyfelek Google-on keresnek ügyvédet, nem ajánlás alapján – weboldal nélkül naponta veszít ügyfeleket',
    gain: 'online konzultáció, professzionális imázs, új ügyfelek a körzetből',
    hook: 'a magyarok 68%-a online keres ügyvédet az első kapcsolatfelvétel előtt',
    urgency: 'a weboldallal rendelkező irodák havonta 5-10 új konzultációt kapnak online-ból',
    waHook: 'new ügyfelek akik ügyvédet keresnek online',
  },
  accounting: {
    pain: 'a fiatal cégek Google-on keresnek könyvelőt – weboldal nélkül nem léteznek számukra',
    gain: 'havonta új ügyfelek, professzionális imázs, kapcsolatfelvételi űrlapok',
    hook: 'a startupok és új vállalkozások kizárólag online keresnek könyvelőt',
    urgency: 'az adóbevallási szezon most van – cégek most keresnek könyvelőt',
    waHook: 'új vállalkozások akik könyvelőt keresnek Google-n',
  },
  painter: {
    pain: 'a festők és kivitelezők weboldal nélkül elveszítik a nagy felújítási megrendeléseket',
    gain: 'munkaportofolió, online ajánlatkérés, hitelességség',
    hook: '"festő [város]" havonta ezreket keresnek a Google-n',
    urgency: 'az építési szezon most van – minden weboldal nélküli hét elveszített pénz',
    waHook: 'online ajánlatkérések felújításokra',
  },
  plumber: {
    pain: 'amikor éjjel 10-kor elromlik a cső, az emberek Google-on keresnek – nem a telefonkönyvben',
    gain: 'azonnali hívások éjjel-nappal, lefedettségi terület, ellenőrzött vélemények',
    hook: '"vízszerelő sürgős [város]" az egyik legtöbbet keresett helyi kifejezés',
    urgency: 'a weboldallal rendelkező vízszerelők 4x annyi új ügyfelet kapnak havonta',
    waHook: 'sürgős hívások Google-ból amikor vízszerelőt keresnek',
  },
  electrician: {
    pain: 'az ügyfelek nem tudják mit kínál, milyen áron és mikor elérhető',
    gain: 'napi új érdeklődők, munkaportofolió, látható munkaterület',
    hook: 'a helyi villanyszerelő keresések 60%-kal nőttek az elmúlt 2 évben',
    urgency: 'weboldal nélkül a potenciális ügyfelek 90%-a nem találja meg',
    waHook: 'new ügyfelek a közelből Google-n keresztül',
  },
  veterinary_care: {
    pain: 'az állatgazdák Google-on keresnek állatorvost vészhelyzet esetén',
    gain: 'online időpontfoglalás, sürgős esetekre 24/7, új hűséges ügyfelek',
    hook: 'Magyarországon 30%-kal nőtt a háziállatok száma az elmúlt 3 évben',
    urgency: 'a weboldallal rendelkező klinikák 3x annyi új időpontot kapnak',
    waHook: 'online időpontfoglalás és sürgős esetekre ügyfelek',
  },
  car_rental: {
    pain: 'az ügyfelek online keresnek autóbérlést és online foglalnak – weboldal nélkül elveszíti a foglalásokat',
    gain: 'közvetlen online foglalás, flotta bemutatása árakkal, hitelességség',
    hook: 'a turizmus és üzleti utazás nő – az autóbérlés kereslet csúcson van nyáron',
    urgency: 'a nyári szezon közeleg – a turisták most foglalnak a konkurenciánál',
    waHook: 'közvetlen foglalások Booking jutalék nélkül',
  },
  towing_service: {
    pain: 'amikor a kocsi meghibásodik, az emberek sürgősen Google-n keresnek vontatót – ott van?',
    gain: 'sürgős Google Maps megjelenés, látható telefonszám, megbízható vélemények',
    hook: '"autómentő sürgős [város]" naponta tízszer keresik',
    urgency: 'minden weboldal nélküli nap = sürgős ügyfelek akik a konkurenciához mennek',
    waHook: 'sürgős vontatási hívások – az első legyen Google-n',
  },
  default: {
    pain: 'a potenciális ügyfelek nem találják online és a weboldallal rendelkező konkurenciához mennek',
    gain: '24/7 online láthatóság, havonta új ügyfelek, professzionális imázs',
    hook: 'a fogyasztók 97%-a online keres helyi szolgáltatásokat vásárlás előtt',
    urgency: 'minden weboldal nélküli nap egy nap amikor az ügyfelek a konkurenciához mennek',
    waHook: 'new ügyfelek Google-ről minden nap',
  },
}
